### ISSUE TITLE
Does not work for me on PLF 4.X

### ISSUE THREAD

**Issue by teknologist** [exo-addons/maintenance-warning-addon#1]
Installed through ./addon install
Then I followed tutorial. Set an event.
No error, nothing. I can see the event in calendar an homepage right side portlet but Popup never shows.

I have seen it work on community.exoplatform.com

Many thanks

**Comment by boubaker** [comment]
Fixed by commit:
https://github.com/exo-addons/maintenance-warning-addon/commit/b13b62575808cbae6dc52eca8daac2bbe625d407

See updated README file.

**Comment by teknologist** [comment]
Hi!

It seems to work at last!

Now, there is a typo in your readme:

%remainig_time% should be %remaining_time% I guess...

**Comment by boubaker** [comment]
Thank you very much for your contribution. It's fixed now.

**Comment by teknologist** [comment]
Weird...I still get this:

![screen shot 2016-08-17 at 12 31 47](https://cloud.githubusercontent.com/assets/148448/17733405/aa0bab2c-6476-11e6-8cc6-e5d5ddee8ecd.PNG)

**Comment by teknologist** [comment]
Oops! Working now, The second notification did replace the remaining_time field

**Comment by teknologist** [comment]
The remaining time calculation is wrong... I have set timezone properly to GMT+1...

Let me know whatever you need to help you solve it. I am currently hacking some addons/skin so I am in full debug mode... ;-)
See below:

![screen shot 2016-08-17 at 12 47 05](https://cloud.githubusercontent.com/assets/148448/17733824/d17ef568-6478-11e6-9aed-75ef66c574ff.PNG)

**Comment by boubaker** [comment]
What are the system, jvm and maintenance calendar timezones ?

**Comment by teknologist** [comment]
Hi,

JDK 1.8 OSX (my dev machine)

eXo 4.3

GMT+1 Timezone
I also have this:

CATALINA_OPTS="${CATALINA_OPTS} -Dfile.encoding=UTF-8 -Duser.timezone=Europe/Paris -Dsun.jnu.encoding=utf-8"

**Comment by boubaker** [comment]
What is the timezone of the "Maintenance"calendar:

![select Maintenance calendar](https://raw.githubusercontent.com/exo-addons/maintenance-warning-addon/master/resource/ScreenShots/1_TimeZone.png)

**Comment by teknologist** [comment]
As I said , twice ;-) :

![screen shot 2016-08-17 at 14 49 23](https://cloud.githubusercontent.com/assets/148448/17736749/d76e809a-6489-11e6-8e33-8b564405d9cd.PNG)
![screen shot 2016-08-17 at 14 48 37](https://cloud.githubusercontent.com/assets/148448/17736750/d782f3f4-6489-11e6-9ee6-1cca47425053.PNG)

**Comment by boubaker** [comment]
ok, I see, I have changed something in master. Can you please test it and tell me if it's ok for you.
Thank you in advance.

**Comment by teknologist** [comment]
Hi,

Brilliant!

Works like a charm now!

Many thanks!

**Comment by boubaker** [comment]
Thank you very much for your precious help :+1:

**Comment by teknologist** [comment]
My pleasure  :-)
